GET http://localhost:8080/players

###

GET http://localhost:8080/players/player3

###

POST localhost:8080/players
Content-Type: application/json

{
  "username": "player3",
  "fullName": "Pierre Jojo",
  "email": "pierre@example.com"
}

###


PUT localhost:8080/players/player3
Content-Type: application/json

{
  "fullName": "Pierre Joeur",
  "email": "pierre@example.com"
}

###

DELETE http://localhost:8080/players/player3